name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      services:
        postgres:
          image: postgres:latest
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: login_db_panache        # Ersätt med ditt databasnamn
            POSTGRES_USER: user        # Ersätt med ditt användarnamn
            POSTGRES_PASSWORD: password  # Ersätt med ditt lösenord
          options: >-
            --health-cmd "pg_isready -U user" 
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ./gradlew  # Steg för att sätta körbarhetsrättigheter

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test -Dquarkus.profile=test --info  # Använd rätt profil och mer information
