name: Java CI

# Definierar när workflow ska köras
on:
  push:
    branches: [ "master" ] # Workflow triggas vid push på master
  pull_request:
    branches: [ "master" ] # Workflow triggas vis pull_request på master

# Definierar jobben som ska köras
jobs:
  build:

    # Specificerar vilken typ av operativsystem som ska användas
    runs-on: ubuntu-latest

    # Definierar tjänster som behövs för jobbet
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: login_db_panache        # Ersätt med ditt databasnamn
          POSTGRES_USER: user        # Ersätt med ditt användarnamn
          POSTGRES_PASSWORD: password  # Ersätt med ditt lösenord
        options: >-
          --health-cmd "pg_isready -U user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    # Stegen som kommer att köras i jobbet
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ./gradlew  # gör gradlew körbar

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test -Dquarkus.profile=test --info  # Använd rätt profil och mer information
